### ISSUE TITLE
usage guide

### ISSUE THREAD

**Issue by lengjingworld** [WGLab/LinkedSV#1]
Is there any documentation that I can follow to try out this software?

**Comment by fangli80** [comment]
Hi, thank you for using LinkedSV. I am adding some new features to the software and will update the software with documentation in a few days. 

Best, 
Li

**Comment by galeoni** [comment]
Hi, 

 following lengjingworld question,
may you also provide documentation on the outputs files that linkedSV generates?

Thanks in advance,
Gabriele

**Comment by fangli80** [comment]
Hi, the format of the output file is described in the readme file. I also update the software. Please clone the latest version. 

Best, 
Li
