### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by woodoo46** [WGLab/LinkedSV#16]
Hi there,

I gave the program 20 cores and 100g memory to run, for the first few hours of run, it used only about 30G memory or so. Then it suddenly jumped to quite some memory. I had this:

=>> PBS: job killed: vmem 176121253888 exceeded limit 107374182400
It seems it requires 170G memory?

The following is the command before the job got killed:
[main] CMD: /home/user/LinkedSV/fermikit/fermi.kit/bwa index /home/user/10X_sv/linkedsv/hg002_w_blacklist/region_000016/region_000016.fasta
[main] Real time: 0.102 sec; CPU: 0.065 sec
[fai_load] build FASTA index.

Thanks!

George

**Comment by fangli80** [comment]
Hi, 
It seems that LinkedSV was calling fermitkit to do local assembly and the assembly of one local region used that much memory. This region might be a repeat region that has ultra high coverage. skipping such region should be ok. I can modify the code and set a hard limit for the assembly process.  

Thanks, 
Li

**Comment by woodoo46** [comment]
OK. It might be caused by some small contigs in the reference genome. When you were analyzing HG002, did you use only main chromosomes? And how much running time is it for a sample? In my case, it had been running more than 4 days. Is it normal?

THanks.

**Comment by woodoo46** [comment]
One more question, what is the relationship of hg38.2D.blacklist.gz and hg38_black_list.bed? In the command line, for option --black_region_bed, I assume we use hg38_black_list.bed? I added two more lines in your file hg38_black_list.bed,

chrX	3524000	3526000
chrX	68652000	68654000
chrY	10626000	11040000
chrY	11290000	11332000
**chrEBV	0	171823
hs38d1	0	10560522**

Is it enough for the program to exclude those two regions? Thanks!

**Comment by fangli80** [comment]
4 days are too long. I think it stuck in the assembly of some weird regions. I'll let you know after I modifed the code. 

Both `hg38.2D.blacklist.gz` and `hg38_black_list.bed` should be used. There is a `alternative_contigs.txt` file in the `black_lists` folder which already added `chrEBV` and `hs38d1 `. If you are using hg38, you don't need to specify the black list files manually. You should use the `-v hg38` option to specify the reference version and LinkedSV will automatically use the correct black list files. By the way, it is important to use the reference genome provided by 10X genomics (the `refdata-GRCh38-2.1.0`). 

The `hg38.2D.blacklist.gz` and `hg38_black_list.bed` are explained here: 
The `hg38.2D.blacklist.gz` is a list of **window pairs** between which the barcode overlapping are ignored.  For example, the first 3 lines of  `hg38.2D.blacklist.gz`  are: 

```
#bin_size=2000
>chr15,chr20
19806000        62000,64000,31074000
```
It means the barcode overlapping between following regions are ignored. 
```
chr15:19806000-19808000  and chr20:62000-64000
chr15:19806000-19808000  and chr20:64000-66000
chr15:19806000-19808000  and chr20:31074000-31076000
```

But the barcode overlapping between `chr15:19806000-19808000` and any other genomic regions will not be ignored. 

The `hg38_black_list.bed` is a list of regions that may cause issues in too many regions, and are blocked directly.  For example, the first line of `hg38_black_list.bed` is:
```
chr1	10000	12000
```
It means the barcode overlapping between `chr1:10000-12000` and any other genomic regions are ignored. 

Thanks, 
Li

**Comment by woodoo46** [comment]
linkedsv.py \\
        -i ${bamfile} \\
        -d ${outdir}  \\
        -r ${genome}  \\
        -v ${hgbuild} \\
        -t ${threads} \\
        --gap_region_bed ${PREFIX}/hg38_gap.bed \\
        --black_region_bed my_hg38_black_list.bed \\
        --germline_mode

Here is the command I used to run on hg002, where $genome is 10X reference genome, and my_hg38_black_list.bed is the one I modified by adding two more lines. Is the command reasonable?

**Comment by woodoo46** [comment]
I had the program finished correctly, I think, other than complains of fonts in the drawing functions. I have the following files/folder:

images/
phased_possorted_bam.bam.bcd21.gz
phased_possorted_bam.bam.filtered_large_svcalls.bedpe
phased_possorted_bam.bam.large_cnv.bedpe
phased_possorted_bam.bam.small_deletions.bedpe

**Comment by fangli80** [comment]
Yes. That results look correct. How did you solve the memory issue ?

**Comment by woodoo46** [comment]
I used less cores and large memory.

**Comment by fangli80** [comment]
Thank you.
