### ISSUE TITLE
What does DUP mean in the result?

### ISSUE THREAD

**Issue by woodoo46** [WGLab/LinkedSV#17]
Hi Li,

Does DUP mean the same thing in *filtered_large_svcalls.bedpe and *large_cnv.bedpe? For example, for SV, most callers refer TANDEM DUP as DUP; in CNV, DUP is NOT necessarily tandem dup, it could be an interspersed insertion.

Thanks for clarification.

**Comment by fangli80** [comment]
In the `filtered_large_svcalls.bedpe` file, DUP means large tandem duplications, 
In the `large_cnv.bedpe` file, DUP means copy number agains detected from read depth.
