### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by FrickTobias** [WGLab/LinkedSV#7]
## Problem

I've noticed the `pip install` command does not work as intended and results in error. It seems to come from four listed modules which won't be found by pip.

**Modules causing errors**
- math
- subprocess
- gzip
- bisect

## Solution

Simply remove these from from the command as these modules are included in the [python standard library](https://docs.python.org/3/library/), meaning any installation of python should include these. 

## Explicit command & errors

```
$ pip install --user bisect
Collecting bisect
  ERROR: Could not find a version that satisfies the requirement bisect (from versions: none)
ERROR: No matching distribution found for bisect
$ pip install --user math
Collecting math
  ERROR: Could not find a version that satisfies the requirement math (from versions: none)
ERROR: No matching distribution found for math
$ pip install --user gzip
Collecting gzip
  ERROR: Could not find a version that satisfies the requirement gzip (from versions: none)
ERROR: No matching distribution found for gzip
$ pip install --user subprocess
Collecting subprocess
  ERROR: Could not find a version that satisfies the requirement subprocess (from versions: none)
ERROR: No matching distribution found for subprocess
```

**Comment by fangli80** [comment]
Thank you!  I have updated the documentation.

**Comment by fangli80** [comment]
By the way, LinkedSV calls Fermikit to do local assembly based SV detection. The assembly sometimes failed in extremely low or high coverage regions and core.XXXX files may be generated. In general, this should have little effect on the final results. I updated the script to remove the core.XXXX files and If you see the core files you can just remove them.
